# .github/workflows/deploy.yml

name: Deploy GitHub Pages site

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["remove_homepage_dir"] # Or "master"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skip runs queued in-progress
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Set up Node.js
      #   uses: actions/setup-node@v4
        # with:
        #   node-version: 20 # Use a current LTS version
        #   cache: 'npm'
      #- name: set up vite
      #  run: npm install -D vite
      #- name: testing dependencies
      #  run: npm install -D tailwindcss@3 
      #- name: install autoprefixer 
      #  run: npm install autoprefixer
      #- name: install postcss
      #  run: npm install postcss 
      # - name: initialize tailwindcss
      #   run: npx tailwindcss init -p
      #- name: Install dependencies
      #  run: npm install --include=dev
      - name: everything
        run: npm install && npm install -D tailwindcss@3 postcss@latest autoprefixer@latest && jsc -b && vite build
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the 'dist' folder (Vite's default build output)
          path: './dist'
      - name: list artifact files
        run: ls -R ./dist

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4